language: php

sudo: required
addons:
  firefox: latest

services:
  - mysql

stages:
  - behat
  - test
  - quality

jobs:
  include:
    - stage: test
      php: '5.4'
      env: COMPOSER=composer-php-5-4.json
      script: ./vendor/bin/phpunit -c ./phpunit.xml.dist
    - stage: test
      php: '5.5'
      env: COMPOSER=composer-php-5-4.json
      script: ./vendor/bin/phpunit -c ./phpunit.xml.dist
    - stage: test
      php: '5.6'
      env: COMPOSER=composer-php-5-4.json
      script: ./vendor/bin/phpunit -c ./phpunit.xml.dist
    - stage: test
      php: '7.0'
      script: ./vendor/bin/phpunit -c ./phpunit.xml.dist
    - stage: test
      php: '7.2'
      script: ./vendor/bin/phpunit -c ./phpunit.xml.dist
    - stage: test
      php: '7.3'
      script: ./vendor/bin/phpunit -c ./phpunit.xml.dist
    - stage: behat
      php: '7.3'
      env: WORDPRESS_VERSION=nightly
      script: ./bin/behat.sh
    - stage: behat
      php: '7.1'
      env: WORDPRESS_VERSION=latest
      script: ./bin/behat.sh
    - stage: behat
      php: '7.2'
      env: WORDPRESS_VERSION=4.9
      script: ./bin/behat.sh
    - stage: behat
      php: '7.1'
      env: WORDPRESS_VERSION=4.8
      script: ./bin/behat.sh
    - stage: behat
      php: '7.1'
      env: WORDPRESS_VERSION=4.7
      script: ./bin/behat.sh
    - stage: behat
      php: '7.0'
      env: WORDPRESS_VERSION=4.6
      script: ./bin/behat.sh
    - stage: behat
      php: '7.0'
      env: WORDPRESS_VERSION=5.0
      script: ./bin/behat.sh
    - stage: behat
      php: '7.0'
      env: WORDPRESS_VERSION=5.1
      script: ./bin/behat.sh
    - stage: behat
      php: '7.0'
      env: WORDPRESS_VERSION=5.2
      script: ./bin/behat.sh
    - stage: quality
      php: '7.0'
      script: ./vendor/bin/phpcs ./ --standard=./phpcs.config.xml -s

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install

# We should also add codecov.
#after_success:
#- bash <(curl -s https://codecov.io/bash)
